// <auto-generated />
using System;
using GenTree.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApi.GenTree.Migrations
{
    [DbContext(typeof(GenTreeContext))]
    partial class GenTreeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenTree.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Given")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("GenTree.Domain.Entities.PersonRelation", b =>
                {
                    b.Property<Guid>("TopPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DownPersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelationLevel")
                        .HasColumnType("integer");

                    b.HasKey("TopPersonId", "DownPersonId");

                    b.HasIndex("DownPersonId");

                    b.HasIndex("TopPersonId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("GenTree.Domain.Entities.PersonRelation", b =>
                {
                    b.HasOne("GenTree.Domain.Entities.Person", "DownPerson")
                        .WithMany("DownRelations")
                        .HasForeignKey("DownPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenTree.Domain.Entities.Person", "TopPerson")
                        .WithMany("TopRelations")
                        .HasForeignKey("TopPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DownPerson");

                    b.Navigation("TopPerson");
                });

            modelBuilder.Entity("GenTree.Domain.Entities.Person", b =>
                {
                    b.Navigation("DownRelations");

                    b.Navigation("TopRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
